font_family JetBrainsMono Nerd Font
font_size 16
disable_ligatures never

background_opacity 0.8
background #181818
foreground #ffffff

color0 #313539
color1 #b30707
color2 #49d932
color3 #f2e635
color4 #4057db
color5 #b30ad0
color6 #32d0fc
color7 #e0e3e7

color8 #676f78
color9 #e81a1a
color10 #78a670
color11 #faf380
color12 #707fd0
color13 #c583d0
color14 #1eb5e3
color15 #e0e3e7
