# -*- conf -*-

term=foot

font=JetBrainsMono Nerd Font:size=16
font-bold=JetBrainsMono Nerd Font:style=Bold:size=16
font-italic=JetBrainsMono Nerd Font:style=Italic:size=16
font-bold-italic=JetBrainsMono Nerd Font:style=Bold Italic:size=16
font-size-adjustment=1.2
gamma-correct-blending=no
selection-target=clipboard

[environment]

[scrollback]
# lines=1000
# multiplier=3.0
# indicator-position=relative
# indicator-format=""

[mouse]
hide-when-typing=yes

[colors-dark]
alpha=0.3
alpha-mode=default
background=181818
foreground=ffffff

regular0=313539
regular1=b30707
regular2=49d932
regular3=f2e635
regular4=4057db
regular5=b30ad0
regular6=32d0fc
regular7=acadb1

bright0=676f78
bright1=e81a1a
bright2=78a670
bright3=faf380
bright4=707fd0
bright5=c583d0
bright6=1eb5e3
bright7=e0e3e7

[csd]
preferred=none
size=0
